### PR TITLE
Added a REGISTRIES environment variable for multi-registry logins

### PR DESCRIPTION
**Pull request by bigkraig**
Patch is bigger than I expected, but I didn't see how to limit what Godeps includes. It could just be that AWS SDK now has more needs.

I flushed out building the params so that you can log into multiple accounts.

### CODE REVIEW

**Comment by bigkraig** [comment]
Hey @rlister any chance of pulling this into the official docker image?

**Comment by rlister** [comment]
@bigkraig Thanks for doing this. The Godeps-giant-patch issue is highly annoying I agree. I'm going to try and dig through this tomorrow so I can merge.

**Comment by bigkraig** [comment]
@rlister what do you think?

**Comment by rlister** [comment]
@bigkraig Really sorry, I am currently traveling and haven't had a chance to look into this yet. I should be able to figure out the patch next week on my return.

**Comment by bigkraig** [comment]
@rlister psst!!!

**Comment by rlister** [comment]
@bigkraig Thanks for the reminder.

I see the problem with the vendored deps. I want to merge your code changes but don't want to merge the 7 billion vendored files and mess up history. I also don't want to merge the import lines for _your_ local deps.

I think the best plan would be either:
- you make a new branch with just the `REGISTRY` changes and create a new PR from that instead, so you can retain credit for the PR
- I can pull your commit to a local branch and cherry-pick from that myself

Which do you prefer? Thanks.

**Comment by rlister** [comment]
Closed in favour of #3

**Pull request closed without merging**
